package com.mb.main.system.mapper;

import com.mb.main.system.model.BEnterprise;
import com.mb.main.system.model.BEnterpriseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BEnterpriseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_enterprise
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	int countByExample(BEnterpriseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_enterprise
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	int deleteByExample(BEnterpriseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_enterprise
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	int deleteByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_enterprise
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	int insert(BEnterprise record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_enterprise
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	int insertSelective(BEnterprise record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_enterprise
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	List<BEnterprise> selectByExampleWithBLOBs(BEnterpriseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_enterprise
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	List<BEnterprise> selectByExample(BEnterpriseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_enterprise
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	BEnterprise selectByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_enterprise
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	int updateByExampleSelective(@Param("record") BEnterprise record, @Param("example") BEnterpriseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_enterprise
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") BEnterprise record, @Param("example") BEnterpriseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_enterprise
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	int updateByExample(@Param("record") BEnterprise record, @Param("example") BEnterpriseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_enterprise
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	int updateByPrimaryKeySelective(BEnterprise record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_enterprise
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(BEnterprise record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_enterprise
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	int updateByPrimaryKey(BEnterprise record);
}