package com.mb.main.system.mapper;

import com.mb.main.system.model.BIndustry;
import com.mb.main.system.model.BIndustryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BIndustryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_industry
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int countByExample(BIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_industry
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int deleteByExample(BIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_industry
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_industry
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int insert(BIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_industry
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int insertSelective(BIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_industry
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    List<BIndustry> selectByExample(BIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_industry
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    BIndustry selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_industry
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int updateByExampleSelective(@Param("record") BIndustry record, @Param("example") BIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_industry
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int updateByExample(@Param("record") BIndustry record, @Param("example") BIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_industry
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int updateByPrimaryKeySelective(BIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_industry
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int updateByPrimaryKey(BIndustry record);
}