package com.mb.main.system.mapper;

import com.mb.main.system.model.BService;
import com.mb.main.system.model.BServiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BServiceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	int countByExample(BServiceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	int deleteByExample(BServiceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	int deleteByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	int insert(BService record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	int insertSelective(BService record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	List<BService> selectByExample(BServiceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	BService selectByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	int updateByExampleSelective(@Param("record") BService record, @Param("example") BServiceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	int updateByExample(@Param("record") BService record, @Param("example") BServiceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	int updateByPrimaryKeySelective(BService record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	int updateByPrimaryKey(BService record);
}