package com.mb.main.system.mapper;

import com.mb.main.system.model.BServiceAdvance;
import com.mb.main.system.model.BServiceAdvanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BServiceAdvanceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service_advance
	 * @mbggenerated  Thu May 26 15:22:09 CST 2016
	 */
	int countByExample(BServiceAdvanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service_advance
	 * @mbggenerated  Thu May 26 15:22:09 CST 2016
	 */
	int deleteByExample(BServiceAdvanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service_advance
	 * @mbggenerated  Thu May 26 15:22:09 CST 2016
	 */
	int deleteByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service_advance
	 * @mbggenerated  Thu May 26 15:22:09 CST 2016
	 */
	int insert(BServiceAdvance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service_advance
	 * @mbggenerated  Thu May 26 15:22:09 CST 2016
	 */
	int insertSelective(BServiceAdvance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service_advance
	 * @mbggenerated  Thu May 26 15:22:09 CST 2016
	 */
	List<BServiceAdvance> selectByExample(BServiceAdvanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service_advance
	 * @mbggenerated  Thu May 26 15:22:09 CST 2016
	 */
	BServiceAdvance selectByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service_advance
	 * @mbggenerated  Thu May 26 15:22:09 CST 2016
	 */
	int updateByExampleSelective(@Param("record") BServiceAdvance record, @Param("example") BServiceAdvanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service_advance
	 * @mbggenerated  Thu May 26 15:22:09 CST 2016
	 */
	int updateByExample(@Param("record") BServiceAdvance record, @Param("example") BServiceAdvanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service_advance
	 * @mbggenerated  Thu May 26 15:22:09 CST 2016
	 */
	int updateByPrimaryKeySelective(BServiceAdvance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table b_service_advance
	 * @mbggenerated  Thu May 26 15:22:09 CST 2016
	 */
	int updateByPrimaryKey(BServiceAdvance record);
}