package com.mb.main.system.mapper;

import com.mb.main.system.model.DEnterpriseServiceAdvance;
import com.mb.main.system.model.DEnterpriseServiceAdvanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DEnterpriseServiceAdvanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service_advance
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int countByExample(DEnterpriseServiceAdvanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service_advance
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int deleteByExample(DEnterpriseServiceAdvanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service_advance
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service_advance
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int insert(DEnterpriseServiceAdvance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service_advance
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int insertSelective(DEnterpriseServiceAdvance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service_advance
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    List<DEnterpriseServiceAdvance> selectByExample(DEnterpriseServiceAdvanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service_advance
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    DEnterpriseServiceAdvance selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service_advance
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int updateByExampleSelective(@Param("record") DEnterpriseServiceAdvance record, @Param("example") DEnterpriseServiceAdvanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service_advance
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int updateByExample(@Param("record") DEnterpriseServiceAdvance record, @Param("example") DEnterpriseServiceAdvanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service_advance
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int updateByPrimaryKeySelective(DEnterpriseServiceAdvance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service_advance
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int updateByPrimaryKey(DEnterpriseServiceAdvance record);
}