package com.mb.main.system.mapper;

import com.mb.main.system.model.DEnterpriseService;
import com.mb.main.system.model.DEnterpriseServiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DEnterpriseServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int countByExample(DEnterpriseServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int deleteByExample(DEnterpriseServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int insert(DEnterpriseService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int insertSelective(DEnterpriseService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    List<DEnterpriseService> selectByExampleWithBLOBs(DEnterpriseServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    List<DEnterpriseService> selectByExample(DEnterpriseServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    DEnterpriseService selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int updateByExampleSelective(@Param("record") DEnterpriseService record, @Param("example") DEnterpriseServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") DEnterpriseService record, @Param("example") DEnterpriseServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int updateByExample(@Param("record") DEnterpriseService record, @Param("example") DEnterpriseServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int updateByPrimaryKeySelective(DEnterpriseService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(DEnterpriseService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_service
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int updateByPrimaryKey(DEnterpriseService record);
}