package com.mb.main.system.mapper;

import com.mb.main.system.model.DEnterpriseTryOut;
import com.mb.main.system.model.DEnterpriseTryOutExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DEnterpriseTryOutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_try_out
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int countByExample(DEnterpriseTryOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_try_out
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int deleteByExample(DEnterpriseTryOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_try_out
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_try_out
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int insert(DEnterpriseTryOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_try_out
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int insertSelective(DEnterpriseTryOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_try_out
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    List<DEnterpriseTryOut> selectByExample(DEnterpriseTryOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_try_out
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    DEnterpriseTryOut selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_try_out
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int updateByExampleSelective(@Param("record") DEnterpriseTryOut record, @Param("example") DEnterpriseTryOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_try_out
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int updateByExample(@Param("record") DEnterpriseTryOut record, @Param("example") DEnterpriseTryOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_try_out
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int updateByPrimaryKeySelective(DEnterpriseTryOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_enterprise_try_out
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    int updateByPrimaryKey(DEnterpriseTryOut record);
}