package com.mb.main.system.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.mb.main.system.model.ExceptionRecord;
import com.mb.main.system.model.ExceptionRecordExample;

public interface ExceptionRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exception_record
	 * @mbggenerated  Mon May 09 16:00:17 CST 2016
	 */
	int countByExample(ExceptionRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exception_record
	 * @mbggenerated  Mon May 09 16:00:17 CST 2016
	 */
	int deleteByExample(ExceptionRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exception_record
	 * @mbggenerated  Mon May 09 16:00:17 CST 2016
	 */
	int insert(ExceptionRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exception_record
	 * @mbggenerated  Mon May 09 16:00:17 CST 2016
	 */
	int insertSelective(ExceptionRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exception_record
	 * @mbggenerated  Mon May 09 16:00:17 CST 2016
	 */
	List<ExceptionRecord> selectByExample(ExceptionRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exception_record
	 * @mbggenerated  Mon May 09 16:00:17 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ExceptionRecord record, @Param("example") ExceptionRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exception_record
	 * @mbggenerated  Mon May 09 16:00:17 CST 2016
	 */
	int updateByExample(@Param("record") ExceptionRecord record, @Param("example") ExceptionRecordExample example);
}