package com.mb.main.system.mapper;

import com.mb.main.system.model.REnterpriseLoginHistory;
import com.mb.main.system.model.REnterpriseLoginHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface REnterpriseLoginHistoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table r_enterprise_login_history
	 * @mbggenerated  Sat Jun 04 09:54:30 CST 2016
	 */
	int countByExample(REnterpriseLoginHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table r_enterprise_login_history
	 * @mbggenerated  Sat Jun 04 09:54:30 CST 2016
	 */
	int deleteByExample(REnterpriseLoginHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table r_enterprise_login_history
	 * @mbggenerated  Sat Jun 04 09:54:30 CST 2016
	 */
	int deleteByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table r_enterprise_login_history
	 * @mbggenerated  Sat Jun 04 09:54:30 CST 2016
	 */
	int insert(REnterpriseLoginHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table r_enterprise_login_history
	 * @mbggenerated  Sat Jun 04 09:54:30 CST 2016
	 */
	int insertSelective(REnterpriseLoginHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table r_enterprise_login_history
	 * @mbggenerated  Sat Jun 04 09:54:30 CST 2016
	 */
	List<REnterpriseLoginHistory> selectByExample(REnterpriseLoginHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table r_enterprise_login_history
	 * @mbggenerated  Sat Jun 04 09:54:30 CST 2016
	 */
	REnterpriseLoginHistory selectByPrimaryKey(String guid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table r_enterprise_login_history
	 * @mbggenerated  Sat Jun 04 09:54:30 CST 2016
	 */
	int updateByExampleSelective(@Param("record") REnterpriseLoginHistory record, @Param("example") REnterpriseLoginHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table r_enterprise_login_history
	 * @mbggenerated  Sat Jun 04 09:54:30 CST 2016
	 */
	int updateByExample(@Param("record") REnterpriseLoginHistory record, @Param("example") REnterpriseLoginHistoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table r_enterprise_login_history
	 * @mbggenerated  Sat Jun 04 09:54:30 CST 2016
	 */
	int updateByPrimaryKeySelective(REnterpriseLoginHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table r_enterprise_login_history
	 * @mbggenerated  Sat Jun 04 09:54:30 CST 2016
	 */
	int updateByPrimaryKey(REnterpriseLoginHistory record);
}