package com.mb.main.system.mapper;

import com.mb.main.system.model.RIndustryGenerateHistory;
import com.mb.main.system.model.RIndustryGenerateHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RIndustryGenerateHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_industry_generate_history
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    int countByExample(RIndustryGenerateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_industry_generate_history
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    int deleteByExample(RIndustryGenerateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_industry_generate_history
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_industry_generate_history
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    int insert(RIndustryGenerateHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_industry_generate_history
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    int insertSelective(RIndustryGenerateHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_industry_generate_history
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    List<RIndustryGenerateHistory> selectByExampleWithBLOBs(RIndustryGenerateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_industry_generate_history
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    List<RIndustryGenerateHistory> selectByExample(RIndustryGenerateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_industry_generate_history
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    RIndustryGenerateHistory selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_industry_generate_history
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    int updateByExampleSelective(@Param("record") RIndustryGenerateHistory record, @Param("example") RIndustryGenerateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_industry_generate_history
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") RIndustryGenerateHistory record, @Param("example") RIndustryGenerateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_industry_generate_history
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    int updateByExample(@Param("record") RIndustryGenerateHistory record, @Param("example") RIndustryGenerateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_industry_generate_history
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    int updateByPrimaryKeySelective(RIndustryGenerateHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_industry_generate_history
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(RIndustryGenerateHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_industry_generate_history
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    int updateByPrimaryKey(RIndustryGenerateHistory record);
}