package com.mb.main.system.mapper;

import com.mb.main.system.model.VEnterpriseLogin;
import com.mb.main.system.model.VEnterpriseLoginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VEnterpriseLoginMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_enterprise_login
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	int countByExample(VEnterpriseLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_enterprise_login
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	int deleteByExample(VEnterpriseLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_enterprise_login
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	int insert(VEnterpriseLogin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_enterprise_login
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	int insertSelective(VEnterpriseLogin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_enterprise_login
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	List<VEnterpriseLogin> selectByExample(VEnterpriseLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_enterprise_login
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	int updateByExampleSelective(@Param("record") VEnterpriseLogin record, @Param("example") VEnterpriseLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_enterprise_login
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	int updateByExample(@Param("record") VEnterpriseLogin record, @Param("example") VEnterpriseLoginExample example);
}