package com.mb.main.system.model;

import com.mb.main.system.base.BaseModel;

public class BAgents extends BaseModel{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String guid;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_agents.id
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_agents.b_agents_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String bAgentsGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_agents.account
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String account = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_agents.passwd
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String passwd = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_agents.serial_no
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String serialNo = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_agents.uniform_number
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String uniformNumber = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_agents.company_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String companyName = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_agents.company_phone
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String companyPhone = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_agents.company_address
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String companyAddress = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_agents.contact_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String contactName = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_agents.contact_mobile
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String contactMobile = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_agents.contact_email
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String contactEmail = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_agents.remittance_bank
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String remittanceBank = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_agents.remittance_account
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String remittanceAccount = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_agents.remittance_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String remittanceName = "";


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_agents.remark
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String remark = "";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_agents.id
     *
     * @return the value of b_agents.id
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_agents.id
     *
     * @param id the value for b_agents.id
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_agents.b_agents_guid
     *
     * @return the value of b_agents.b_agents_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getbAgentsGuid() {
        return bAgentsGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_agents.b_agents_guid
     *
     * @param bAgentsGuid the value for b_agents.b_agents_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setbAgentsGuid(String bAgentsGuid) {
        this.bAgentsGuid = bAgentsGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_agents.account
     *
     * @return the value of b_agents.account
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_agents.account
     *
     * @param account the value for b_agents.account
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_agents.passwd
     *
     * @return the value of b_agents.passwd
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_agents.passwd
     *
     * @param passwd the value for b_agents.passwd
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_agents.serial_no
     *
     * @return the value of b_agents.serial_no
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_agents.serial_no
     *
     * @param serialNo the value for b_agents.serial_no
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_agents.uniform_number
     *
     * @return the value of b_agents.uniform_number
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getUniformNumber() {
        return uniformNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_agents.uniform_number
     *
     * @param uniformNumber the value for b_agents.uniform_number
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setUniformNumber(String uniformNumber) {
        this.uniformNumber = uniformNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_agents.company_name
     *
     * @return the value of b_agents.company_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_agents.company_name
     *
     * @param companyName the value for b_agents.company_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_agents.company_phone
     *
     * @return the value of b_agents.company_phone
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getCompanyPhone() {
        return companyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_agents.company_phone
     *
     * @param companyPhone the value for b_agents.company_phone
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setCompanyPhone(String companyPhone) {
        this.companyPhone = companyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_agents.company_address
     *
     * @return the value of b_agents.company_address
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_agents.company_address
     *
     * @param companyAddress the value for b_agents.company_address
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_agents.contact_name
     *
     * @return the value of b_agents.contact_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_agents.contact_name
     *
     * @param contactName the value for b_agents.contact_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_agents.contact_mobile
     *
     * @return the value of b_agents.contact_mobile
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getContactMobile() {
        return contactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_agents.contact_mobile
     *
     * @param contactMobile the value for b_agents.contact_mobile
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setContactMobile(String contactMobile) {
        this.contactMobile = contactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_agents.contact_email
     *
     * @return the value of b_agents.contact_email
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getContactEmail() {
        return contactEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_agents.contact_email
     *
     * @param contactEmail the value for b_agents.contact_email
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_agents.remittance_bank
     *
     * @return the value of b_agents.remittance_bank
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getRemittanceBank() {
        return remittanceBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_agents.remittance_bank
     *
     * @param remittanceBank the value for b_agents.remittance_bank
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setRemittanceBank(String remittanceBank) {
        this.remittanceBank = remittanceBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_agents.remittance_account
     *
     * @return the value of b_agents.remittance_account
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getRemittanceAccount() {
        return remittanceAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_agents.remittance_account
     *
     * @param remittanceAccount the value for b_agents.remittance_account
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setRemittanceAccount(String remittanceAccount) {
        this.remittanceAccount = remittanceAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_agents.remittance_name
     *
     * @return the value of b_agents.remittance_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getRemittanceName() {
        return remittanceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_agents.remittance_name
     *
     * @param remittanceName the value for b_agents.remittance_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setRemittanceName(String remittanceName) {
        this.remittanceName = remittanceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_agents.remark
     *
     * @return the value of b_agents.remark
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_agents.remark
     *
     * @param remark the value for b_agents.remark
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

	public String getGuid() {
		return guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}
}