package com.mb.main.system.model;

import com.mb.main.system.base.BaseModel;

public class BEnterprise extends BaseModel{
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_enterprise.id
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_enterprise.store_no
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	private String storeNo = "";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_enterprise.b_agents_guid
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	private String bAgentsGuid = "";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_enterprise.account
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	private String account = "";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_enterprise.b_industry_guid
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	private String bIndustryGuid = "";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_enterprise.uniform_number
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	private String uniformNumber = "";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_enterprise.company_name
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	private String companyName = "";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_enterprise.company_phone
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	private String companyPhone = "";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_enterprise.company_address
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	private String companyAddress = "";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_enterprise.applicant_name
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	private String applicantName = "";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_enterprise.applicant_mobile
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	private String applicantMobile = "";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_enterprise.applicant_email
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	private String applicantEmail = "";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_enterprise.email
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	private String email = "";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_enterprise.email_validate
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	private Integer emailValidate = 1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_enterprise.number_of_employees
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	private Integer numberOfEmployees = 5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_enterprise.status
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	private Integer status = 1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_enterprise.remark
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	private String remark = "";

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_enterprise.id
	 * @return  the value of b_enterprise.id
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_enterprise.id
	 * @param id  the value for b_enterprise.id
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_enterprise.store_no
	 * @return  the value of b_enterprise.store_no
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public String getStoreNo() {
		return storeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_enterprise.store_no
	 * @param storeNo  the value for b_enterprise.store_no
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public void setStoreNo(String storeNo) {
		this.storeNo = storeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_enterprise.b_agents_guid
	 * @return  the value of b_enterprise.b_agents_guid
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public String getbAgentsGuid() {
		return bAgentsGuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_enterprise.b_agents_guid
	 * @param bAgentsGuid  the value for b_enterprise.b_agents_guid
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public void setbAgentsGuid(String bAgentsGuid) {
		this.bAgentsGuid = bAgentsGuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_enterprise.account
	 * @return  the value of b_enterprise.account
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_enterprise.account
	 * @param account  the value for b_enterprise.account
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_enterprise.b_industry_guid
	 * @return  the value of b_enterprise.b_industry_guid
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public String getbIndustryGuid() {
		return bIndustryGuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_enterprise.b_industry_guid
	 * @param bIndustryGuid  the value for b_enterprise.b_industry_guid
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public void setbIndustryGuid(String bIndustryGuid) {
		this.bIndustryGuid = bIndustryGuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_enterprise.uniform_number
	 * @return  the value of b_enterprise.uniform_number
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public String getUniformNumber() {
		return uniformNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_enterprise.uniform_number
	 * @param uniformNumber  the value for b_enterprise.uniform_number
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public void setUniformNumber(String uniformNumber) {
		this.uniformNumber = uniformNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_enterprise.company_name
	 * @return  the value of b_enterprise.company_name
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_enterprise.company_name
	 * @param companyName  the value for b_enterprise.company_name
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_enterprise.company_phone
	 * @return  the value of b_enterprise.company_phone
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public String getCompanyPhone() {
		return companyPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_enterprise.company_phone
	 * @param companyPhone  the value for b_enterprise.company_phone
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public void setCompanyPhone(String companyPhone) {
		this.companyPhone = companyPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_enterprise.company_address
	 * @return  the value of b_enterprise.company_address
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public String getCompanyAddress() {
		return companyAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_enterprise.company_address
	 * @param companyAddress  the value for b_enterprise.company_address
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public void setCompanyAddress(String companyAddress) {
		this.companyAddress = companyAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_enterprise.applicant_name
	 * @return  the value of b_enterprise.applicant_name
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public String getApplicantName() {
		return applicantName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_enterprise.applicant_name
	 * @param applicantName  the value for b_enterprise.applicant_name
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public void setApplicantName(String applicantName) {
		this.applicantName = applicantName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_enterprise.applicant_mobile
	 * @return  the value of b_enterprise.applicant_mobile
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public String getApplicantMobile() {
		return applicantMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_enterprise.applicant_mobile
	 * @param applicantMobile  the value for b_enterprise.applicant_mobile
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public void setApplicantMobile(String applicantMobile) {
		this.applicantMobile = applicantMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_enterprise.applicant_email
	 * @return  the value of b_enterprise.applicant_email
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public String getApplicantEmail() {
		return applicantEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_enterprise.applicant_email
	 * @param applicantEmail  the value for b_enterprise.applicant_email
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public void setApplicantEmail(String applicantEmail) {
		this.applicantEmail = applicantEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_enterprise.email
	 * @return  the value of b_enterprise.email
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_enterprise.email
	 * @param email  the value for b_enterprise.email
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_enterprise.email_validate
	 * @return  the value of b_enterprise.email_validate
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public Integer getEmailValidate() {
		return emailValidate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_enterprise.email_validate
	 * @param emailValidate  the value for b_enterprise.email_validate
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public void setEmailValidate(Integer emailValidate) {
		this.emailValidate = emailValidate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_enterprise.number_of_employees
	 * @return  the value of b_enterprise.number_of_employees
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public Integer getNumberOfEmployees() {
		return numberOfEmployees;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_enterprise.number_of_employees
	 * @param numberOfEmployees  the value for b_enterprise.number_of_employees
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public void setNumberOfEmployees(Integer numberOfEmployees) {
		this.numberOfEmployees = numberOfEmployees;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_enterprise.status
	 * @return  the value of b_enterprise.status
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_enterprise.status
	 * @param status  the value for b_enterprise.status
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_enterprise.remark
	 * @return  the value of b_enterprise.remark
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_enterprise.remark
	 * @param remark  the value for b_enterprise.remark
	 * @mbggenerated  Fri May 27 14:03:45 CST 2016
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}