package com.mb.main.system.model;

import com.mb.main.system.base.BaseModel;

public class BEnterpriseEmployee extends BaseModel{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_enterprise_employee.id
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_enterprise_employee.b_enterprise_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String bEnterpriseGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_enterprise_employee.account
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_enterprise_employee.email
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_enterprise_employee.status
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private Integer status = 50;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_enterprise_employee.id
     *
     * @return the value of b_enterprise_employee.id
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_enterprise_employee.id
     *
     * @param id the value for b_enterprise_employee.id
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_enterprise_employee.b_enterprise_guid
     *
     * @return the value of b_enterprise_employee.b_enterprise_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getbEnterpriseGuid() {
        return bEnterpriseGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_enterprise_employee.b_enterprise_guid
     *
     * @param bEnterpriseGuid the value for b_enterprise_employee.b_enterprise_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setbEnterpriseGuid(String bEnterpriseGuid) {
        this.bEnterpriseGuid = bEnterpriseGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_enterprise_employee.account
     *
     * @return the value of b_enterprise_employee.account
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_enterprise_employee.account
     *
     * @param account the value for b_enterprise_employee.account
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_enterprise_employee.email
     *
     * @return the value of b_enterprise_employee.email
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_enterprise_employee.email
     *
     * @param email the value for b_enterprise_employee.email
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_enterprise_employee.status
     *
     * @return the value of b_enterprise_employee.status
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_enterprise_employee.status
     *
     * @param status the value for b_enterprise_employee.status
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}