package com.mb.main.system.model;

import java.util.Date;

public class BIndustry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.id
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.serial_no
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.sort_no
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private Integer sortNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.is_invalid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private Integer isInvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.creator_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String creatorGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.creator_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.creator_date
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private Date creatorDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.modifier_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String modifierGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.modifier_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String modifierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.modifier_date
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private Date modifierDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.invalid_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String invalidGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.invalid_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String invalidName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_industry.invalid_date
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private Date invalidDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_industry.guid
     *
     * @return the value of b_industry.guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_industry.guid
     *
     * @param guid the value for b_industry.guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setGuid(String guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_industry.id
     *
     * @return the value of b_industry.id
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_industry.id
     *
     * @param id the value for b_industry.id
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_industry.serial_no
     *
     * @return the value of b_industry.serial_no
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_industry.serial_no
     *
     * @param serialNo the value for b_industry.serial_no
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_industry.name
     *
     * @return the value of b_industry.name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_industry.name
     *
     * @param name the value for b_industry.name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_industry.sort_no
     *
     * @return the value of b_industry.sort_no
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_industry.sort_no
     *
     * @param sortNo the value for b_industry.sort_no
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_industry.is_invalid
     *
     * @return the value of b_industry.is_invalid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public Integer getIsInvalid() {
        return isInvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_industry.is_invalid
     *
     * @param isInvalid the value for b_industry.is_invalid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setIsInvalid(Integer isInvalid) {
        this.isInvalid = isInvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_industry.creator_guid
     *
     * @return the value of b_industry.creator_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getCreatorGuid() {
        return creatorGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_industry.creator_guid
     *
     * @param creatorGuid the value for b_industry.creator_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setCreatorGuid(String creatorGuid) {
        this.creatorGuid = creatorGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_industry.creator_name
     *
     * @return the value of b_industry.creator_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_industry.creator_name
     *
     * @param creatorName the value for b_industry.creator_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_industry.creator_date
     *
     * @return the value of b_industry.creator_date
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public Date getCreatorDate() {
        return creatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_industry.creator_date
     *
     * @param creatorDate the value for b_industry.creator_date
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setCreatorDate(Date creatorDate) {
        this.creatorDate = creatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_industry.modifier_guid
     *
     * @return the value of b_industry.modifier_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getModifierGuid() {
        return modifierGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_industry.modifier_guid
     *
     * @param modifierGuid the value for b_industry.modifier_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setModifierGuid(String modifierGuid) {
        this.modifierGuid = modifierGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_industry.modifier_name
     *
     * @return the value of b_industry.modifier_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_industry.modifier_name
     *
     * @param modifierName the value for b_industry.modifier_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_industry.modifier_date
     *
     * @return the value of b_industry.modifier_date
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public Date getModifierDate() {
        return modifierDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_industry.modifier_date
     *
     * @param modifierDate the value for b_industry.modifier_date
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setModifierDate(Date modifierDate) {
        this.modifierDate = modifierDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_industry.invalid_guid
     *
     * @return the value of b_industry.invalid_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getInvalidGuid() {
        return invalidGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_industry.invalid_guid
     *
     * @param invalidGuid the value for b_industry.invalid_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setInvalidGuid(String invalidGuid) {
        this.invalidGuid = invalidGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_industry.invalid_name
     *
     * @return the value of b_industry.invalid_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getInvalidName() {
        return invalidName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_industry.invalid_name
     *
     * @param invalidName the value for b_industry.invalid_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setInvalidName(String invalidName) {
        this.invalidName = invalidName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_industry.invalid_date
     *
     * @return the value of b_industry.invalid_date
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public Date getInvalidDate() {
        return invalidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_industry.invalid_date
     *
     * @param invalidDate the value for b_industry.invalid_date
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setInvalidDate(Date invalidDate) {
        this.invalidDate = invalidDate;
    }
}