package com.mb.main.system.model;

import java.util.Date;

public class BService {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_service.guid
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	private String guid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_service.id
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_service.b_service_category_guid
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	private String bServiceCategoryGuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_service.serial_no
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	private String serialNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_service.title
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_service.sort_no
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	private Integer sortNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_service.url
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_service.is_invalid
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	private Integer isInvalid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_service.creator_guid
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	private String creatorGuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_service.creator_name
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	private String creatorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_service.creator_date
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	private Date creatorDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_service.modifier_guid
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	private String modifierGuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_service.modifier_name
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	private String modifierName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_service.modifier_date
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	private Date modifierDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_service.invalid_guid
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	private String invalidGuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_service.invalid_name
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	private String invalidName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column b_service.invalid_date
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	private Date invalidDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_service.guid
	 * @return  the value of b_service.guid
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public String getGuid() {
		return guid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_service.guid
	 * @param guid  the value for b_service.guid
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public void setGuid(String guid) {
		this.guid = guid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_service.id
	 * @return  the value of b_service.id
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_service.id
	 * @param id  the value for b_service.id
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_service.b_service_category_guid
	 * @return  the value of b_service.b_service_category_guid
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public String getbServiceCategoryGuid() {
		return bServiceCategoryGuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_service.b_service_category_guid
	 * @param bServiceCategoryGuid  the value for b_service.b_service_category_guid
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public void setbServiceCategoryGuid(String bServiceCategoryGuid) {
		this.bServiceCategoryGuid = bServiceCategoryGuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_service.serial_no
	 * @return  the value of b_service.serial_no
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public String getSerialNo() {
		return serialNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_service.serial_no
	 * @param serialNo  the value for b_service.serial_no
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_service.title
	 * @return  the value of b_service.title
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_service.title
	 * @param title  the value for b_service.title
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_service.sort_no
	 * @return  the value of b_service.sort_no
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public Integer getSortNo() {
		return sortNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_service.sort_no
	 * @param sortNo  the value for b_service.sort_no
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public void setSortNo(Integer sortNo) {
		this.sortNo = sortNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_service.url
	 * @return  the value of b_service.url
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_service.url
	 * @param url  the value for b_service.url
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_service.is_invalid
	 * @return  the value of b_service.is_invalid
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public Integer getIsInvalid() {
		return isInvalid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_service.is_invalid
	 * @param isInvalid  the value for b_service.is_invalid
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public void setIsInvalid(Integer isInvalid) {
		this.isInvalid = isInvalid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_service.creator_guid
	 * @return  the value of b_service.creator_guid
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public String getCreatorGuid() {
		return creatorGuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_service.creator_guid
	 * @param creatorGuid  the value for b_service.creator_guid
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public void setCreatorGuid(String creatorGuid) {
		this.creatorGuid = creatorGuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_service.creator_name
	 * @return  the value of b_service.creator_name
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public String getCreatorName() {
		return creatorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_service.creator_name
	 * @param creatorName  the value for b_service.creator_name
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public void setCreatorName(String creatorName) {
		this.creatorName = creatorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_service.creator_date
	 * @return  the value of b_service.creator_date
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public Date getCreatorDate() {
		return creatorDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_service.creator_date
	 * @param creatorDate  the value for b_service.creator_date
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public void setCreatorDate(Date creatorDate) {
		this.creatorDate = creatorDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_service.modifier_guid
	 * @return  the value of b_service.modifier_guid
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public String getModifierGuid() {
		return modifierGuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_service.modifier_guid
	 * @param modifierGuid  the value for b_service.modifier_guid
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public void setModifierGuid(String modifierGuid) {
		this.modifierGuid = modifierGuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_service.modifier_name
	 * @return  the value of b_service.modifier_name
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public String getModifierName() {
		return modifierName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_service.modifier_name
	 * @param modifierName  the value for b_service.modifier_name
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public void setModifierName(String modifierName) {
		this.modifierName = modifierName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_service.modifier_date
	 * @return  the value of b_service.modifier_date
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public Date getModifierDate() {
		return modifierDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_service.modifier_date
	 * @param modifierDate  the value for b_service.modifier_date
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public void setModifierDate(Date modifierDate) {
		this.modifierDate = modifierDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_service.invalid_guid
	 * @return  the value of b_service.invalid_guid
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public String getInvalidGuid() {
		return invalidGuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_service.invalid_guid
	 * @param invalidGuid  the value for b_service.invalid_guid
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public void setInvalidGuid(String invalidGuid) {
		this.invalidGuid = invalidGuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_service.invalid_name
	 * @return  the value of b_service.invalid_name
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public String getInvalidName() {
		return invalidName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_service.invalid_name
	 * @param invalidName  the value for b_service.invalid_name
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public void setInvalidName(String invalidName) {
		this.invalidName = invalidName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column b_service.invalid_date
	 * @return  the value of b_service.invalid_date
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public Date getInvalidDate() {
		return invalidDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column b_service.invalid_date
	 * @param invalidDate  the value for b_service.invalid_date
	 * @mbggenerated  Sat Jun 04 20:49:55 CST 2016
	 */
	public void setInvalidDate(Date invalidDate) {
		this.invalidDate = invalidDate;
	}
}