package com.mb.main.system.model;

import java.util.Date;

public class DEnterpriseServiceAdvance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_enterprise_service_advance.guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_enterprise_service_advance.id
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_enterprise_service_advance.b_service_advance_gui d
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String bServiceAdvanceGuiD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_enterprise_service_advance.b_enterprise_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String bEnterpriseGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_enterprise_service_advance.start_time
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_enterprise_service_advance.end_time
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_enterprise_service_advance.is_invalid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private Integer isInvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_enterprise_service_advance.creator_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String creatorGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_enterprise_service_advance.creator_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_enterprise_service_advance.creator_date
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private Date creatorDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_enterprise_service_advance.modifier_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String modifierGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_enterprise_service_advance.modifier_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String modifierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_enterprise_service_advance.modifier_date
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private Date modifierDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_enterprise_service_advance.invalid_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String invalidGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_enterprise_service_advance.invalid_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private String invalidName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_enterprise_service_advance.invalid_date
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    private Date invalidDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_enterprise_service_advance.guid
     *
     * @return the value of d_enterprise_service_advance.guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_enterprise_service_advance.guid
     *
     * @param guid the value for d_enterprise_service_advance.guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setGuid(String guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_enterprise_service_advance.id
     *
     * @return the value of d_enterprise_service_advance.id
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_enterprise_service_advance.id
     *
     * @param id the value for d_enterprise_service_advance.id
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_enterprise_service_advance.b_service_advance_gui d
     *
     * @return the value of d_enterprise_service_advance.b_service_advance_gui d
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getbServiceAdvanceGuiD() {
        return bServiceAdvanceGuiD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_enterprise_service_advance.b_service_advance_gui d
     *
     * @param bServiceAdvanceGuiD the value for d_enterprise_service_advance.b_service_advance_gui d
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setbServiceAdvanceGuiD(String bServiceAdvanceGuiD) {
        this.bServiceAdvanceGuiD = bServiceAdvanceGuiD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_enterprise_service_advance.b_enterprise_guid
     *
     * @return the value of d_enterprise_service_advance.b_enterprise_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getbEnterpriseGuid() {
        return bEnterpriseGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_enterprise_service_advance.b_enterprise_guid
     *
     * @param bEnterpriseGuid the value for d_enterprise_service_advance.b_enterprise_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setbEnterpriseGuid(String bEnterpriseGuid) {
        this.bEnterpriseGuid = bEnterpriseGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_enterprise_service_advance.start_time
     *
     * @return the value of d_enterprise_service_advance.start_time
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_enterprise_service_advance.start_time
     *
     * @param startTime the value for d_enterprise_service_advance.start_time
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_enterprise_service_advance.end_time
     *
     * @return the value of d_enterprise_service_advance.end_time
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_enterprise_service_advance.end_time
     *
     * @param endTime the value for d_enterprise_service_advance.end_time
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_enterprise_service_advance.is_invalid
     *
     * @return the value of d_enterprise_service_advance.is_invalid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public Integer getIsInvalid() {
        return isInvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_enterprise_service_advance.is_invalid
     *
     * @param isInvalid the value for d_enterprise_service_advance.is_invalid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setIsInvalid(Integer isInvalid) {
        this.isInvalid = isInvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_enterprise_service_advance.creator_guid
     *
     * @return the value of d_enterprise_service_advance.creator_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getCreatorGuid() {
        return creatorGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_enterprise_service_advance.creator_guid
     *
     * @param creatorGuid the value for d_enterprise_service_advance.creator_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setCreatorGuid(String creatorGuid) {
        this.creatorGuid = creatorGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_enterprise_service_advance.creator_name
     *
     * @return the value of d_enterprise_service_advance.creator_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_enterprise_service_advance.creator_name
     *
     * @param creatorName the value for d_enterprise_service_advance.creator_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_enterprise_service_advance.creator_date
     *
     * @return the value of d_enterprise_service_advance.creator_date
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public Date getCreatorDate() {
        return creatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_enterprise_service_advance.creator_date
     *
     * @param creatorDate the value for d_enterprise_service_advance.creator_date
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setCreatorDate(Date creatorDate) {
        this.creatorDate = creatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_enterprise_service_advance.modifier_guid
     *
     * @return the value of d_enterprise_service_advance.modifier_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getModifierGuid() {
        return modifierGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_enterprise_service_advance.modifier_guid
     *
     * @param modifierGuid the value for d_enterprise_service_advance.modifier_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setModifierGuid(String modifierGuid) {
        this.modifierGuid = modifierGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_enterprise_service_advance.modifier_name
     *
     * @return the value of d_enterprise_service_advance.modifier_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_enterprise_service_advance.modifier_name
     *
     * @param modifierName the value for d_enterprise_service_advance.modifier_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_enterprise_service_advance.modifier_date
     *
     * @return the value of d_enterprise_service_advance.modifier_date
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public Date getModifierDate() {
        return modifierDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_enterprise_service_advance.modifier_date
     *
     * @param modifierDate the value for d_enterprise_service_advance.modifier_date
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setModifierDate(Date modifierDate) {
        this.modifierDate = modifierDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_enterprise_service_advance.invalid_guid
     *
     * @return the value of d_enterprise_service_advance.invalid_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getInvalidGuid() {
        return invalidGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_enterprise_service_advance.invalid_guid
     *
     * @param invalidGuid the value for d_enterprise_service_advance.invalid_guid
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setInvalidGuid(String invalidGuid) {
        this.invalidGuid = invalidGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_enterprise_service_advance.invalid_name
     *
     * @return the value of d_enterprise_service_advance.invalid_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public String getInvalidName() {
        return invalidName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_enterprise_service_advance.invalid_name
     *
     * @param invalidName the value for d_enterprise_service_advance.invalid_name
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setInvalidName(String invalidName) {
        this.invalidName = invalidName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_enterprise_service_advance.invalid_date
     *
     * @return the value of d_enterprise_service_advance.invalid_date
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public Date getInvalidDate() {
        return invalidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_enterprise_service_advance.invalid_date
     *
     * @param invalidDate the value for d_enterprise_service_advance.invalid_date
     *
     * @mbggenerated Thu May 26 15:22:09 CST 2016
     */
    public void setInvalidDate(Date invalidDate) {
        this.invalidDate = invalidDate;
    }
}