package com.mb.main.system.model;

import java.util.Date;

public class RIndustryGenerateHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_industry_generate_history.guid
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_industry_generate_history.id
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_industry_generate_history.b_agents_guid
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    private String bAgentsGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_industry_generate_history.quantity
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    private String quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_industry_generate_history.is_invalid
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    private Integer isInvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_industry_generate_history.creator_guid
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    private String creatorGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_industry_generate_history.creator_name
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_industry_generate_history.creator_date
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    private Date creatorDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_industry_generate_history.modifier_guid
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    private String modifierGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_industry_generate_history.modifier_name
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    private String modifierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_industry_generate_history.modifier_date
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    private Date modifierDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_industry_generate_history.invalid_guid
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    private String invalidGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_industry_generate_history.invalid_name
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    private String invalidName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_industry_generate_history.invalid_date
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    private Date invalidDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_industry_generate_history.store_no_list
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    private String storeNoList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_industry_generate_history.guid
     *
     * @return the value of r_industry_generate_history.guid
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_industry_generate_history.guid
     *
     * @param guid the value for r_industry_generate_history.guid
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public void setGuid(String guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_industry_generate_history.id
     *
     * @return the value of r_industry_generate_history.id
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_industry_generate_history.id
     *
     * @param id the value for r_industry_generate_history.id
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_industry_generate_history.b_agents_guid
     *
     * @return the value of r_industry_generate_history.b_agents_guid
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public String getbAgentsGuid() {
        return bAgentsGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_industry_generate_history.b_agents_guid
     *
     * @param bAgentsGuid the value for r_industry_generate_history.b_agents_guid
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public void setbAgentsGuid(String bAgentsGuid) {
        this.bAgentsGuid = bAgentsGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_industry_generate_history.quantity
     *
     * @return the value of r_industry_generate_history.quantity
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public String getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_industry_generate_history.quantity
     *
     * @param quantity the value for r_industry_generate_history.quantity
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_industry_generate_history.is_invalid
     *
     * @return the value of r_industry_generate_history.is_invalid
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public Integer getIsInvalid() {
        return isInvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_industry_generate_history.is_invalid
     *
     * @param isInvalid the value for r_industry_generate_history.is_invalid
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public void setIsInvalid(Integer isInvalid) {
        this.isInvalid = isInvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_industry_generate_history.creator_guid
     *
     * @return the value of r_industry_generate_history.creator_guid
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public String getCreatorGuid() {
        return creatorGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_industry_generate_history.creator_guid
     *
     * @param creatorGuid the value for r_industry_generate_history.creator_guid
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public void setCreatorGuid(String creatorGuid) {
        this.creatorGuid = creatorGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_industry_generate_history.creator_name
     *
     * @return the value of r_industry_generate_history.creator_name
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_industry_generate_history.creator_name
     *
     * @param creatorName the value for r_industry_generate_history.creator_name
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_industry_generate_history.creator_date
     *
     * @return the value of r_industry_generate_history.creator_date
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public Date getCreatorDate() {
        return creatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_industry_generate_history.creator_date
     *
     * @param creatorDate the value for r_industry_generate_history.creator_date
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public void setCreatorDate(Date creatorDate) {
        this.creatorDate = creatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_industry_generate_history.modifier_guid
     *
     * @return the value of r_industry_generate_history.modifier_guid
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public String getModifierGuid() {
        return modifierGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_industry_generate_history.modifier_guid
     *
     * @param modifierGuid the value for r_industry_generate_history.modifier_guid
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public void setModifierGuid(String modifierGuid) {
        this.modifierGuid = modifierGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_industry_generate_history.modifier_name
     *
     * @return the value of r_industry_generate_history.modifier_name
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_industry_generate_history.modifier_name
     *
     * @param modifierName the value for r_industry_generate_history.modifier_name
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_industry_generate_history.modifier_date
     *
     * @return the value of r_industry_generate_history.modifier_date
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public Date getModifierDate() {
        return modifierDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_industry_generate_history.modifier_date
     *
     * @param modifierDate the value for r_industry_generate_history.modifier_date
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public void setModifierDate(Date modifierDate) {
        this.modifierDate = modifierDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_industry_generate_history.invalid_guid
     *
     * @return the value of r_industry_generate_history.invalid_guid
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public String getInvalidGuid() {
        return invalidGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_industry_generate_history.invalid_guid
     *
     * @param invalidGuid the value for r_industry_generate_history.invalid_guid
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public void setInvalidGuid(String invalidGuid) {
        this.invalidGuid = invalidGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_industry_generate_history.invalid_name
     *
     * @return the value of r_industry_generate_history.invalid_name
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public String getInvalidName() {
        return invalidName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_industry_generate_history.invalid_name
     *
     * @param invalidName the value for r_industry_generate_history.invalid_name
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public void setInvalidName(String invalidName) {
        this.invalidName = invalidName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_industry_generate_history.invalid_date
     *
     * @return the value of r_industry_generate_history.invalid_date
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public Date getInvalidDate() {
        return invalidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_industry_generate_history.invalid_date
     *
     * @param invalidDate the value for r_industry_generate_history.invalid_date
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public void setInvalidDate(Date invalidDate) {
        this.invalidDate = invalidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_industry_generate_history.store_no_list
     *
     * @return the value of r_industry_generate_history.store_no_list
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public String getStoreNoList() {
        return storeNoList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_industry_generate_history.store_no_list
     *
     * @param storeNoList the value for r_industry_generate_history.store_no_list
     *
     * @mbggenerated Thu May 26 15:22:10 CST 2016
     */
    public void setStoreNoList(String storeNoList) {
        this.storeNoList = storeNoList;
    }
}