package com.mb.main.system.model;

public class VEnterpriseLogin {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_enterprise_login.pk
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	private String pk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_enterprise_login.store_no
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	private String storeNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_enterprise_login.account
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_enterprise_login.passwd
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	private String passwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_enterprise_login.token
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	private String token;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_enterprise_login.type
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_enterprise_login.status
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	private Long status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_enterprise_login.pk
	 * @return  the value of v_enterprise_login.pk
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	public String getPk() {
		return pk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_enterprise_login.pk
	 * @param pk  the value for v_enterprise_login.pk
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	public void setPk(String pk) {
		this.pk = pk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_enterprise_login.store_no
	 * @return  the value of v_enterprise_login.store_no
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	public String getStoreNo() {
		return storeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_enterprise_login.store_no
	 * @param storeNo  the value for v_enterprise_login.store_no
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	public void setStoreNo(String storeNo) {
		this.storeNo = storeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_enterprise_login.account
	 * @return  the value of v_enterprise_login.account
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_enterprise_login.account
	 * @param account  the value for v_enterprise_login.account
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_enterprise_login.passwd
	 * @return  the value of v_enterprise_login.passwd
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	public String getPasswd() {
		return passwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_enterprise_login.passwd
	 * @param passwd  the value for v_enterprise_login.passwd
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_enterprise_login.token
	 * @return  the value of v_enterprise_login.token
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_enterprise_login.token
	 * @param token  the value for v_enterprise_login.token
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	public void setToken(String token) {
		this.token = token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_enterprise_login.type
	 * @return  the value of v_enterprise_login.type
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_enterprise_login.type
	 * @param type  the value for v_enterprise_login.type
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_enterprise_login.status
	 * @return  the value of v_enterprise_login.status
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	public Long getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_enterprise_login.status
	 * @param status  the value for v_enterprise_login.status
	 * @mbggenerated  Sat Jun 04 09:43:06 CST 2016
	 */
	public void setStatus(Long status) {
		this.status = status;
	}
}